"""categories and journalEntry

Revision ID: 5e46c4fd76fa
Revises: e9476243e2a1
Create Date: 2024-07-08 18:15:06.250074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e46c4fd76fa'
down_revision = 'e9476243e2a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entry_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entry_user_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_date'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_category_id'))

    op.drop_table('journal_entry')
    op.drop_table('category')
    # ### end Alembic commands ###
